apiVersion: 1

deleteDataSources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  acces: proxy
  orgId: 1
  url: localhost:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true